### ISSUE TITLE
deinit() is immediately called after init

### ISSUE THREAD

**Issue by eonist** [soh335/FileWatch#1]
Your code works. Awesome!

But i had to comment out the deinit call. I guess deinit is taken care of by swift now?

**Comment by soh335** [comment]
I guess that instance is destroyed soon after initialized in your program. [This test code](https://github.com/soh335/FileWatch/blob/master/FileWatchTests/FileWatchTests.swift#L26-L54) is worked at my environment and travis-ci. Is it worked your environment ?

**Comment by eonist** [comment]
I will do some digging on stackoverflow and get back to you.

**Comment by eonist** [comment]
Cant find any info on this on stackoverflow either must be an isolated case.
