### ISSUE TITLE
Event callback not being fired

### ISSUE THREAD

**Issue by WarTech9** [soh335/FileWatch#3]
I copied the FileWatch.swift file into my app and using it to monitor folders on OSX 10.11.6. I start monitoring file system events without any errors but noticed the callback never gets called. My initial app was sandboxed, so thinking that could have something to do with it, I created a test app, copied the code in, without any changes, and got the same results. Callback events are not fired. 

Also added the FileWatchTests file and  run the tests; the `testFileCreate` test fails after the timeout, because the event callback is not called before timeout expires. Here's the test output

    Test Suite 'Selected tests' started at 2016-12-09 00:00:10.505
    Test Suite 'TodoListTests.xctest' started at 2016-12-09 00:00:10.506
    Test Suite 'FileWatchTests' started at 2016-12-09 00:00:10.506
    Test Case '-[TodoListTests.FileWatchTests testInitCreateFlag]' started.
    Test Case '-[TodoListTests.FileWatchTests testInitCreateFlag]' passed (0.001 seconds).
    Test Case '-[TodoListTests.FileWatchTests testFileCreate]' started.
    file:///var/folders/hq/0bs9lngs3x79f31k1tndcxbm0000gn/T/AEE80BF5-A560-47C7-B8DD-F0E34BF69E31-75021-0002DAC9BBDDE8A4_file.txt
    /************/TodoList/TodoListTests/FileWatchTests.swift:63: error: 
    -[TodoListTests.FileWatchTests testFileCreate] : 
    Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "".
    Test Case '-[TodoListTests.FileWatchTests testFileCreate]' failed (10.171 seconds).
    Test Suite 'FileWatchTests' failed at 2016-12-09 00:00:20.679.
	 Executed 2 tests, with 1 failure (0 unexpected) in 10.172 (10.173) seconds
    Test Suite 'TodoListTests.xctest' failed at 2016-12-09 00:00:20.680.
	 Executed 2 tests, with 1 failure (0 unexpected) in 10.172 (10.174) seconds
    Test Suite 'Selected tests' failed at 2016-12-09 00:00:20.680.
	 Executed 2 tests, with 1 failure (0 unexpected) in 10.172 (10.175) seconds

Any ideas why this would happen?

**Comment by soh335** [comment]
Clone this project and running test is same result ?
I pass test on 10.12.1, now. And I created this project on 10.11, so maybe work.

**Comment by WarTech9** [comment]
After cloning the project, the tests do pass. Looks more like a memory issue. 
Line 36:
    
    let fileWatch = try! FileWatch(paths: [(tmpfile.path as NSString).deletingLastPathComponent], createFlag: [.UseCFTypes, .FileEvents], runLoop: RunLoop.current, latency: 3.0, eventHandler: {

Swift gives a warning since the `fileWatch` constant is unused. So I had changed it to `_` to get rid of the warning:

    let _ = try! FileWatch(paths: [(tmpfile.path as NSString).deletingLastPathComponent], createFlag: [.UseCFTypes, .FileEvents], runLoop: RunLoop.current, latency: 3.0, eventHandler: {

So that fails due to the FileWatch object getting deallocated, but the original code is fine. So most likely is a memory issue after all. 
I'm taking a closer look at my original project.

**Comment by WarTech9** [comment]
Looks like I had a couple issues in my code. First one was the memory issue with the `FileWatch` object getting deallocated. Secondly I was  using `url.absoluteString`, instead of `url.path` to get the paths to watch.

After making those changes everything works great  👍🏾
